### ISSUE TITLE
doesn't work with /*!

### ISSUE THREAD

**Issue by romanlex** [mrnocreativity/postcss-critical-split#11]
cssnano doesn't remove any comments with started as `/*!`
but if I put in my sass file this
```
/*! critical:start */

/*! critical:end */
```
criticalSplit not work(

**Comment by andyjansson** [comment]
https://github.com/cssnano/cssnano/tree/master/packages/postcss-discard-comments#removeall

**Comment by mrnocreativity** [comment]
Sorry for the super late reply. I'm currently looking into it. Might push out an update later today!

**Comment by mrnocreativity** [comment]
Just completed work to support comments like that.
It does required the space though.
So `/*!critical*/` will not work. `/*! critical*/` will work. I'll release this later today.
