### ISSUE TITLE
options.output does not have 'critical' as default

### ISSUE THREAD

**Issue by usrbowe** [mrnocreativity/postcss-critical-split#2]
Hi,

in current version its needed to set:` 'output': 'critical'` when creating critical css. Otherwise it will not do anything to source styles.

Also in this usage example, you are missing one parentheses at the end.
`gulp.src(['**/*.css','!**/*-critical.css'])`
`.pipe(postcss(require('postcss-critical-split'));`
should be:
`gulp.src(['**/*.css','!**/*-critical.css'])`
 `   .pipe(postcss(require('postcss-critical-split')));`

Even **options.suffix** doesn't seem to work. 

It would be better if you could update the whole readme.

**Comment by mrnocreativity** [comment]
you're right, the readme is probably not entirely up to date. Quite honestly with the speed and size of the changes that I have been pushing, I have been a bit sloppy with the readme... 

I'm looking into adding a testing setup in the near future. Those tests should also serve as a guide. 

Thanks for your feedback. i'll make sure to address it asap!

**Comment by mrnocreativity** [comment]
I addressed your readme comments in v2.4.1.

I also deprecated the save feature and removed both the save feature and the suffix option from the readme file. In release v3.0.0, these will be removed completely.

I will address the entire readme as soon as I have completed adding testing. 
I'll keep this issue open as long as this process is not completed.

You can follow the work on the `feature/add-testing` branch

**Comment by mrnocreativity** [comment]
I just pushed an update which adds tests and has an adapted readme. With that I'm closing this issue. If something else comes up, please let me know :)
